- app/models/challenge.rb
- app/models/expense.rb
- app/models/monster.rb
- app/models/player.rb
- db/migrate/20230828151232_create_players.rb
- db/migrate/20230828151546_create_challenges.rb
- db/migrate/20230828151547_create_monsters.rb
- db/migrate/20230828151916_create_expenses.rb
- db/migrate/20230828152343_add_expenses_to_challenges.rb
- db/schema.rb
- test/models/challenge_test.rb
- test/models/expense_test.rb
- test/models/monster_test.rb
- test/models/player_test.rb
First iteration of db and models, please feel free to review and comment.
> Add models and create db

- app/controllers/player_controller.rb
- app/views/player/edit.html.erb
- app/views/player/show.html.erb
- app/views/player/update.html.erb
- config/routes.rb
- db/migrate/20230828154442_add_username_to_players.rb
- db/schema.rb
- test/controllers/player_controller_test.rb
I added the username to the player table which we forgot, and then added player controller.
> Add username to player model and add player controller

- app/controllers/challengers_controller.rb
> damage calculation

- app/models/treasure_chest.rb
- db/migrate/20230829145604_create_treasure_chests.rb
- db/schema.rb
- test/models/treasure_chest_test.rb
We added model and migration for the treasure chest feature
> Add model and migration for treasure chests

- app/controllers/players_controller.rb
- app/views/players/_form.html.erb
- app/views/players/create.html.erb
- app/views/shared/_navbar.html.erb
- db/migrate/20230829142128_add_avatar_to_players.rb
- db/migrate/20230829143734_change_avatar_to_players.rb
- db/schema.rb
This Pull request 
Create a mgration to the Players table, including the field :avatar :string
it is a place to save the avatar chosen by the player
> Create Player double migrate

- config/routes.rb
Resolve a conflict with the Routes
> Routes conflict

- db/schema.rb
> Routes conflict_2

- db/migrate/20230830102748_remove_balance_from_players.rb
- db/migrate/20230830104222_add_column_to_challenges.rb
- db/migrate/20230830105804_remove_level_from_monsters.rb
- db/migrate/20230830110214_add_current_value_to_treasue_chests.rb
- db/schema.rb
I changed player, challenges, monsters and treasure chests, adding and for the most part deleting fields and references, so that they better represent our models. Please review and merge, and pull :)
> Major changes to database, please review

- app/controllers/challenges_controller.rb
- app/views/challenges/show.html.erb
- app/views/pages/home.html.erb
Bugfixes to make the challenges work again
> Fix bugs for challenge methods after database changes

- app/models/challenge.rb
- app/models/treasure_chest.rb
- db/migrate/20230830124521_add_default_to_treasure_chests.rb
- db/schema.rb
I added the enums to have the different status for the challenges. Right now we have three different status': "running", "won" and "lost"
> Enum for status

- .gitignore
- Gemfile
- Gemfile.lock
- app/controllers/treasure_chests_controller.rb
- app/models/challenge.rb
- app/views/layouts/application.html.erb
- app/views/pages/cloudinary.html.erb
- config/routes.rb
- test/controllers/treasure_chests_controller_test.rb
Set up cloudinary
added a new route
created treasures controller and treasure chests index
Added a templace to application.html.erb to center all views and forms.
> Treasures frontend

- app/controllers/players_controller.rb
- app/models/player.rb
- app/views/players/_form.html.erb
Just that, player creation works now again with our changed models
> Repair player creation method and adapt to new database

- app/controllers/challenges_controller.rb
- app/models/challenge.rb
- app/views/pages/home.html.erb
> Combat now working

- app/controllers/challenges_controller.rb
- app/controllers/expenses_controller.rb
- app/controllers/players_controller.rb
- app/models/challenge.rb
- app/views/challenges/new.html.erb
- app/views/challenges/show.html.erb
- app/views/expenses/new.html.erb
- config/routes.rb
I added functionality to create expenses from within a challenge. It has not yet been implemented through buttons etc.
> As a user, I can create an expense within my active challenge

- app/controllers/challenges_controller.rb
- app/views/challenges/new.html.erb
- app/views/challenges/show.html.erb
Please review and merge if good :)
> Advanced challenges

- app/controllers/challenges_controller.rb
- app/views/challenges/show.html.erb
- db/seeds.rb
I worked on the resolutions for challenges, possibility to win or lose challenges.
> Work on resolutions for challenges

- app/assets/stylesheets/application.scss
- app/views/treasure_chests/index.html.erb
> minor style update to text

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_backgrounds.scss
- app/views/challenges/create.html.erb
- app/views/challenges/delete.html.erb
- app/views/challenges/edit.html.erb
- app/views/challenges/index.html.erb
- app/views/challenges/show.html.erb
- app/views/challenges/update.html.erb
- app/views/expenses/create.html.erb
- app/views/expenses/delete.html.erb
- app/views/expenses/edit.html.erb
- app/views/expenses/show.html.erb
- app/views/expenses/update.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/home.html.erb
- app/views/players/delete.html.erb
- app/views/players/edit.html.erb
- app/views/players/update.html.erb
- config/routes.rb
deleted hundreds of useless views
styled challenges show
added background to some pages
> deleted useless views. added style

- app/views/players/show.html.erb
> Some changes

- app/views/players/show.html.erb
- db/seeds.rb
Change the seed, and modify Player view!
> Change the seed, again and Player view

- app/models/player.rb
New update , Player  has_one_attached :picture
> Model has one attached picture

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/_backgrounds.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_forms.scss
- app/assets/stylesheets/components/_index.scss
- app/views/challenges/new.html.erb
- app/views/challenges/show.html.erb
- app/views/expenses/new.html.erb
- app/views/pages/home.html.erb
- app/views/pages/index.html.erb
- app/views/players/_form.html.erb
- app/views/players/new.html.erb
- app/views/players/show.html.erb
- app/views/treasure_chests/index.html.erb
> Victor stuff

- app/controllers/players_controller.rb
- app/models/player.rb
- app/views/players/_form.html.erb
- app/views/players/show.html.erb
Asignation the Player to the DB picture
> Player select logic

- app/models/player.rb
- app/views/players/show.html.erb
- db/seeds.rb
connection the Images with the Model,
> Conect the Player with the image

- app/models/monster.rb
> Monster model step 1

- app/assets/stylesheets/components/_buttons.scss
- app/views/challenges/show.html.erb
> fixed challenges show styling

- app/models/monster.rb
> Monster model step 2

- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/components/_status_bar.scss
- app/views/shared/_status_bar.html.erb
> fixed status bar

- app/views/challenges/new.html.erb
- app/views/treasure_chests/index.html.erb
- app/views/treasure_chests/new.html.erb
> fixed many things that were shit before

- app/views/devise/sessions/new.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/_status_bar.html.erb
> made things just better

- app/models/monster.rb
- db/seeds.rb
Update Monster Model, and Update the   Seeds
> Model Monster & seeds

- db/seeds.rb
>  seeds final version

- app/views/players/show.html.erb
added orange text for player name on players/show to match the rest of the styling
> need colored text for player name on player/show

- app/views/shared/_status_bar.html.erb
Actual health and rubies of a player are now display on the navbar, this feature still needs styling.
> Display actual health and rubies on status bar -- needs styling

- app/controllers/challenges_controller.rb
Added behavior so that attack costs rubies. Also negative hitpoints from monsters does not increase player health anymore.
> unbreak attacks

- app/javascript/controllers/datepicker_controller.js
- app/views/challenges/new.html.erb
- app/views/expenses/new.html.erb
- app/views/layouts/application.html.erb
- config/importmap.rb
> flatpickr inplementation -not restriction

- app/controllers/players_controller.rb
- app/models/player.rb
- app/models/user.rb
- app/views/shared/_status_bar.html.erb
I also made it so that a user can only have one player.
> Fix problem with login

- app/views/challenges/show.html.erb
> updated style to challenges show

- app/views/challenges/new.html.erb
- app/views/treasure_chests/show.html.erb
Adding some text , for the User experience!
> modify some text

- app/views/treasure_chests/show.html.erb
> added overflow on this container

- app/views/challenges/show.html.erb
> added overflow

- app/assets/stylesheets/components/_buttons.scss
- app/views/treasure_chests/index.html.erb
Adding the chest to the challenges
> Adding the chest to the challenges

- app/assets/stylesheets/application.scss
- app/views/challenges/show.html.erb
- app/views/players/show.html.erb
- app/views/treasure_chests/show.html.erb
> added text breaks to places that needed them

- app/controllers/challenges_controller.rb
- app/controllers/pages_controller.rb
- app/controllers/treasure_chests_controller.rb
Just a fix to make the player pay with rubies for attacks
> small changes and fixes

- app/views/players/_form.html.erb
Changed input text from "avatar_url" to "Chose your Avatar"
> small text change

- app/views/treasure_chests/show.html.erb
> fixed uncentered text. deleted useless code

- app/assets/stylesheets/application.scss
> imported new fonts

- app/views/challenges/new.html.erb
> fixed text display on challenges new

- app/views/shared/_navbar.html.erb
Added the sword icon to navbar and created the functionality to point to the last created challenge
> Add sword to navbar

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_health_bars.scss
- app/assets/stylesheets/components/_index.scss
- app/views/challenges/show.html.erb
health bars to be implemented later
right now they are at 100% when player is on 100 health. Over 100 health has non dynamic behaviour
Changed enrage the monster and attack links into buttons. Gave them different colours
> added health bars. Restyled monster buttons

- app/views/shared/_status_bar.html.erb
> Modify icons

- app/views/challenges/new.html.erb
- app/views/players/show.html.erb
> fixed non wrapping P text. updated player show

- app/controllers/challenges_controller.rb
- app/controllers/expenses_controller.rb
I added the new behavior for the monster.
> Change monster behavior to be more intuitive

- app/views/shared/_navbar.html.erb
> Changes to navbar

- app/views/players/new.html.erb
> minor fix to players new display

- app/models/challenge.rb
- app/models/expense.rb
- app/models/treasure_chest.rb
added validations for create treasure and challenge to stop blank fields from input
> Validations

- app/javascript/controllers/slider_controller.js
- app/views/expenses/new.html.erb
> slider Second one

- db/production_data.rb
Seeding in Production!
WE DO NOT WANT PROBLEMSTHE DEMO DAY!!, thats why we have a seeding in production
in production we will delete all the data and create 4 Users, (NOT PLAYERS)
To execute seed en production, : 
heroku run RAILS_ENV=production rails db:seed
i will try it tonight
> Seeding in Production

- app/views/expenses/new.html.erb
> Slider update

- app/views/treasure_chests/index.html.erb
> centered text on treasure chest index

- app/views/challenges/show.html.erb
p tag has missing / which caused a large gap in a div
> fixed closing tag causing large gap

- app/javascript/controllers/slider_controller.js
- app/views/treasure_chests/new.html.erb
> Slider update 3

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/components/popup.scss
- app/controllers/challenges_controller.rb
- app/javascript/controllers/notifications_controller.js
- app/views/challenges/show.html.erb
Added a first popup-message that appears when you lose a challenge.
> Add popup for defeat

- app/assets/config/manifest.js
- app/javascript/controllers/challenges_controller.js
- app/views/challenges/show.html.erb
updated stimulus for the challenges enrage the monster page
buttons now animate indepedently and each button plays a different sound
> updated stimulus controller

- app/controllers/treasure_chests_controller.rb
- app/views/treasure_chests/show.html.erb
> chest changes

- app/views/treasure_chests/show.html.erb
> chest changes2

- app/javascript/controllers/notifications_controller.js
- app/views/challenges/show.html.erb
- app/views/treasure_chests/show.html.erb
I changed the button to lead to the new_challenges page again
> Fix for button Embark on new journey

- app/views/treasure_chests/show.html.erb
> fixed styling on treasure chests show

- app/javascript/controllers/challenges_controller.js
- app/views/challenges/show.html.erb
- app/views/treasure_chests/show.html.erb
> fixed minor display issues. Cleaned up JS controller. amended delay

- app/views/treasure_chests/show.html.erb
end was missing breaking website
> fixed missing end

- app/assets/stylesheets/components/_health_bars.scss
- app/views/challenges/show.html.erb
updated health bars to make them more better
> updated health bars

- app/models/challenge.rb
- app/models/expense.rb
- app/views/expenses/new.html.erb
> Validations step 1

- app/controllers/expenses_controller.rb
- app/models/expense.rb
- app/views/challenges/show.html.erb
- app/views/expenses/new.html.erb
- db/migrate/20230906205526_add_category_to_expenses.rb
- db/schema.rb
Adding a migration, new field to the "expenses" table
the name of the field is category,  adding a collection to the model with the restriction, 
adding the dropdown menu , and the view of the category to the Challenge view!
> Categories step1

- app/assets/stylesheets/pages/_landing.scss
- app/views/challenges/new.html.erb
- app/views/devise/sessions/new.html.erb
- app/views/expenses/new.html.erb
- app/views/layouts/graveyard.html
- app/views/players/show.html.erb
- app/views/treasure_chests/index.html.erb
- app/views/treasure_chests/show.html.erb
Edited several texts and some font sizes in different views
> for consistency

- app/views/shared/_status_bar.html.erb
Just a small fix to keep the page working when challenge.id is nil
> small fixes to popup

- app/views/devise/registrations/new.html.erb
- app/views/shared/_status_bar.html.erb
fixed inconsistent button size on sign up
> Signupbtns

- app/controllers/expenses_controller.rb
- app/controllers/players_controller.rb
- app/controllers/treasure_chests_controller.rb
- app/javascript/controllers/buttons_disable_controller.js
- app/views/shared/_navbar.html.erb
Some redirects, may break for old players
> Small fixes

- app/models/challenge.rb
- app/models/expense.rb
- app/models/treasure_chest.rb
- public/404.html
- public/_404.html
> validation not 0

- app/models/challenge.rb
Changed validations to get rid of description on challenges
> fix-sliders

- app/assets/stylesheets/components/_health_bars.scss
- app/javascript/controllers/challenges_controller.js
- app/views/challenges/show.html.erb
> updated monster rage bar. Made icons shake it on attack

- app/assets/stylesheets/components/_backgrounds.scss
> updated background display

- app/views/challenges/show.html.erb
> Lastminuteupdates

- app/models/expense.rb
- app/views/challenges/new.html.erb
- app/views/expenses/new.html.erb
Validation fixed, not monster at expenses
> Validation fixed, not monster at expenses

- app/controllers/expenses_controller.rb
- app/views/expenses/new.html.erb
> Monster update 3

- Gemfile
- Gemfile.lock
- config/initializers/rails_admin.rb
- config/routes.rb
- db/migrate/20230912131202_add_admin_to_users.rb
- db/schema.rb
Updated Treasure Keeper with rails_admin 3.0
-Necessary to bundle
-Necessary to migrate. 
thanks
> Updated with rails_admin 3.0
